### ISSUE TITLE
Not handling packages with different package.json name than folder

### ISSUE THREAD

**Issue by palmerj3** [teambox/npm-shrinkwrap-check#10]
Example: If you include this package in your repo - https://www.npmjs.com/package/asn1.js-rfc5280

This package installs under the folder name "asn1.js" and shrinkwrap creates an entry for it like:

`
"asn1.js": {
      "version": "4.6.2",
      "from": "asn1.js@>=4.0.0 <5.0.0",
      "resolved": "https://registry.npmjs.org/asn1.js/-/asn1.js-4.6.2.tgz"
    },
`

This script will always identify this dependency as out of sync with shrinkwrap because it's only examining package.json name property as key lookup in npm-shrinkwrap.json.

**Comment by Morantron** [comment]
I cannot reproduce it, which versions are you using of `npm` and `npm-shrinkwrap-check`?
