### ISSUE TITLE
Only run if JS related files are being checked in

### ISSUE THREAD

**Issue by joeshub** [teambox/npm-shrinkwrap-check#18]
Would it be possible and make sense to only run this process if files being checked in are javascript files? This would speed up workflow.
- .js
- .json
- .ts

etc.

**Comment by alexindigo** [comment]
HI Joe,

It'd be somewhat out of scope of this project. Users can run shrinkwrap-check at different stage of repo lifecycle or without any relation to git at all. So it'd be more efficient to work on conditional run as part of your app or utilizing some other project.

**Comment by joeshub** [comment]
Thanks Alex, Looks like this project is now deprecated in favor of using Yarn so closing this out.
