### ISSUE TITLE
Feature Request: npm-shrinkwrap-check does not check versions

### ISSUE THREAD

**Issue by rvock** [teambox/npm-shrinkwrap-check#2]
Scenario:
1. My node_modules contains a version 1.0.0 of a package P
2. I get an update to npm-shrinkwrap.json through version control, which requires version 1.0.1 of package P
3. running npm-shrinkwrap-check does not inform me, that my current installed version is incorrect

I know, this is currently not part of npm-shrinkwrap-check, because it only checks that package.json and npm-shrinkwrap.json are in sync. But it would be nice, if it would also check the installed packages in node_modules.

**Comment by Morantron** [comment]
That's a task of `npm shrinkwrap` itself. And extraflag could be added to perform an `npm shrinkwrap` as well, but the main purpose of this tool is to prevent out-of-sync `package.json` and `npm-shrinkwrap.json` in your repo.

Meanwhile maybe `npm shrinkwrap && npm-shrinkwrap-check` can work for you

**Comment by Morantron** [comment]
fixed in version 0.1.0
