### ISSUE TITLE
wish: npm 3 compatibility

### ISSUE THREAD

**Issue by markstos** [teambox/npm-shrinkwrap-check#4]
npm 3 makes a "maximally flat" structure in node_modules, and also in npm-shrinkwrap.json. 

This currently trips up `npm-shrinkwrap-check` which expects every top-level entry in npm-shrinkwrap.json to have an entry in package.json. When they don't, a warning is emitted like this:

`xtend found in npm-shrinkwrap.json but not in package.json`

I get over a hundred of these warnings with my project, leaving significant uncertainly if there are real problems being reported or if the expected behavior of `npm 3` is simply being observed.

**Comment by Morantron** [comment]
Are these `peerDependencies`? In that case it's better if you install the explicitly so they are locked down properly.

Certainly, I need to check with `npm 3` to ensure that everything works OK!

**Comment by mattwynne** [comment]
Did you get a change to try this out on npm 3 @Morantron? This tool looks useful, but we've got a similar situation to @markstos right now making the output too noisy.

**Comment by Morantron** [comment]
@mattwynne @markstos currently working on it, expect an update soon!

**Comment by command-tab** [comment]
Any progress on this?

If I delete `npm-shrinkwrap.json` from my project directory, run `npm shrinkwrap` to generate the shrinkwrap file again, then run `npm-shrinkwrap-check`, I get lots of warnings that I would expect to not see since the shrinkwrap file was freshly re-generated.

**Comment by jeffstieler** [comment]
I just ran into this issue after updating a project to npm 3.

Any word on a solution? Thanks!

**Comment by Morantron** [comment]
Hi! Sorry for the inactivity here, haven't had much time to look into this issue lately :pray: 

I've seen that npm3 is already support in [this fork](https://github.com/mizchi/npm-shrinkwrap-check). I've created a new branch called `npm3-support`.

If you add `"npm-shrinkwrap-check": "teambox/npm3-support"` to your package JSON you'll should be able to test npm3 support. You can give it a try to see if it works for you and should be available in next published version! :tada:

**Comment by Morantron** [comment]
just added npm3 support added in version 0.1.0

**Comment by Morantron** [comment]
Remember to add `-3` as flag when calling `npm-shrinkwrap-check`.
